version: '2.1'

services:
  artifactory:
    image: "docker.bintray.io/jfrog/artifactory-${ARTIFACTORY_LICENSE}:${ARTIFACTORY_VERSION}"
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - "${ARTIFACTORY_COMPOSE_BASE}/${ARTIFACTORY_HOST_DATA}:/var/opt/jfrog/artifactory"
    restart: always
  # nginx:
  #   image: "docker.bintray.io/jfrog/nginx-artifactory-${ARTIFACTORY_LICENSE}:${ARTIFACTORY_VERSION}"
  #   container_name: nginx
  #   ports:
  #    - 80:80
  #    - 443:443
  #   depends_on:
  #    - artifactory
  #   links:
  #    - artifactory
  #   volumes:
  #    - "${ARTIFACTORY_COMPOSE_BASE}/${NGINX_HOST_DATA}:/var/opt/jfrog/nginx"
  #   environment:
  #    - ART_BASE_URL=http://jinhub.com:8081/artifactory
  #    - SSL=true
  #    - RUNTIME_OPTS="-Xms1g -Xmx2g"
  #   restart: always
