version: '2.1'

services:
  jenkins:
    image: mvp-jenkins-master:dev
    network_mode: bridge
    container_name: jenkins
    ports:
      - "${HOST_JNLP}:50000"
      - "${HOST_HTTP}:8080"
    # volumes:
    #   - "${HOST_JENKINS_HOME}:/var/jenkins_home:rw"
    environment:
      # passwordless installation
      # (CPU load fix): -Dgroovy.use.classvalue=true
      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dgroovy.use.classvalue=true"
      JENKINS_HOME_ON_HOST: "${HOST_JENKINS_HOME}"

    external_links:
      - artifactory
