version: '2.1'

services:
  jenkins-worker:
    image: mvp-jenkins-worker:dev
    network_mode: bridge
    # ports:
    #   - "${HOST_JNLP}:50000"
    # volumes:
    #   - "${HOST_JENKINS_HOME}:/var/jenkins_home:rw"
    environment:
      JENKINS_SLAVE_MASTER_SERVER: jenkins
      # passwordless installation
      # (CPU load fix): -Dgroovy.use.classvalue=true
      # JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Dgroovy.use.classvalue=true"
      # JENKINS_HOME_ON_HOST: "${HOST_JENKINS_HOME}"
    external_links:
      - artifactory
      - jenkins
